spring.application.name=SensitiveWords

spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=password123!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect


spring.datasource.host=localhost
spring.datasource.port=1433
spring.datasource.database=expensetracker
spring.datasource.encrypt=true
spring.datasource.trustServerCertificate=true
